namespace AndRod.StronglyTypedIds;

/// <summary>
/// Represents a strongly-typed ID that wraps a value of type <typeparamref name="T"/>.
/// </summary>
public interface IStronglyTypedId<out T>
    where T : struct, IEquatable<T>, IComparable<T>
{
    /// <summary>
    /// Gets the value of the strongly-typed ID.
    /// </summary>
    T Value { get; }
}

/// <summary>
/// Represents a strongly-typed ID that wraps a boxed value of type <see cref="object"/>.
/// </summary>
public interface IStronglyTypedId
{
    /// <summary>
    /// Gets the value of the strongly-typed ID as an <see cref="object"/>.
    /// </summary>
    object Value { get; }

    /// <summary>
    /// Gets the type of the strongly-typed ID class.
    /// </summary>
    Type StronglyTypedIdType { get; }

    /// <summary>
    /// Gets the type of the <see href="Value" />.
    /// </summary>
    Type Type { get; }

    /// <summary>
    /// A transient ID is one that has not yet been assigned a value.
    /// Most common use case is when the ID is generated by the database.
    /// </summary>
    bool IsTransient { get; }
}
